[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_hello_world = "5RToMja5PmpcFjLvtZrtxJozY5xoA3AK6Qdj3aj62wXU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/repanna/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
